// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsyrTGDnxlSkh_PSNshxPJVqjQp1mrHQk',
    appId: '1:108119032594:web:c418ab90eb9df98c50e9cb',
    messagingSenderId: '108119032594',
    projectId: 'swiftcare-eb012',
    authDomain: 'swiftcare-eb012.firebaseapp.com',
    storageBucket: 'swiftcare-eb012.appspot.com',
    measurementId: 'G-J9LE222FX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV2BQgY8qa_9Xvpg1ylqozf_zpUQuBX1U',
    appId: '1:108119032594:android:0578747ac05031ae50e9cb',
    messagingSenderId: '108119032594',
    projectId: 'swiftcare-eb012',
    storageBucket: 'swiftcare-eb012.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbDQBBdm8wPUZe7Vitj0pLFwFHx6q6e_4',
    appId: '1:108119032594:ios:57da391bba27cdb650e9cb',
    messagingSenderId: '108119032594',
    projectId: 'swiftcare-eb012',
    storageBucket: 'swiftcare-eb012.appspot.com',
    iosBundleId: 'com.example.locationGrm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbDQBBdm8wPUZe7Vitj0pLFwFHx6q6e_4',
    appId: '1:108119032594:ios:a10929323b8f952b50e9cb',
    messagingSenderId: '108119032594',
    projectId: 'swiftcare-eb012',
    storageBucket: 'swiftcare-eb012.appspot.com',
    iosBundleId: 'com.example.locationGrm.RunnerTests',
  );
}
